### ISSUE TITLE
Phantom Robot

### ISSUE THREAD

**Issue by BlairRenX** [abrichardson00/SDP-Group-8-Robot#1]
I thought this was a quirk of importing the robot, but it seems to happen on the current store.wbt as well. When the robot is moved, a version of it remains at the origin. I'm unsure of what causes this. Let me know if you experience this bug as well.

**Comment by sandra-tu** [comment]
Oh sorry that's my bad, there's two copies of the platform components, I didn't want to delete the original just in case something went wrong. I wanted to hide the original but couldn't figure out how to 🙈  If you know how to hide objects in Webots please do that.

**Comment by BlairRenX** [comment]
Okay, that's good. I guess I'll find the shape data and see if I can make it stop rendering the duplicate
Although it's not explicitly necessary if we maintain a backup. Will fix tomorrow and push a version without the duplicate.
